#pragma once

#define ALIOTH_VERSION_MAJOR 2
#define ALIOTH_VERSION_MINOR 0
#define ALIOTH_VERSION_PATCH 0

#define ALIOTH_MAX_STUBS 1024
#define ALIOTH_MAX_GADGETS 8
#define ALIOTH_MAX_CHAIN_DEPTH 8
#define MAX_MASK_CANDIDATES 256
#define DECOY_THREAD_COUNT 4
#define CHACHA20_KEY_SIZE 32
#define CHACHA20_NONCE_SIZE 12
#define POLY1305_TAG_SIZE 16

#define ALIOTH_ENABLE_ETW_PATCH 1
#define ALIOTH_ENABLE_HWBP_CHECK 1
#define ALIOTH_ENABLE_DECOY_THREADS 1
#define ALIOTH_ENABLE_SSN_OBFUSCATION 1
#define ALIOTH_ENABLE_GADGET_ROTATION 1
#define ALIOTH_ENABLE_MASK_CHAINS 1
#define ALIOTH_ENABLE_RANDOM_MASKS 1
#define ALIOTH_ENABLE_WIN32U_SYSCALLS 1
#define ALIOTH_ENABLE_STUB_PERMUTATION 1

#define ALIOTH_DEBUG_PRINTS 0
#define ALIOTH_CONSOLE_SUBSYSTEM 1

#if ALIOTH_DEBUG_PRINTS
#define ALIOTH_LOG(fmt, ...) printf("[ALIOTH] " fmt "\n", __VA_ARGS__)
#else
#define ALIOTH_LOG(fmt, ...)
#endif

#define ALIOTH_ERROR(fmt, ...) printf("[ALIOTH ERROR] " fmt "\n", __VA_ARGS__)
